---
- name: Install Generic Packages on Mac
  community.general.homebrew:
    name: '{{ setup_cli_tools_generic_packages }}'
    state: 'present'
  when: 'ansible_facts[''os_family''] == ''Darwin'''

- name: Install Generic Packages on Debian
  ansible.builtin.packages:
    name: '{{ setup_cli_tools_generic_packages }}'
    state: present
  when: 'ansible_facts[''os_family''] == ''Debian'''
...
