---
# You need to install gnu-tar (brew install gnu-tar)
- name: Build URL for Darwin (Mac)
  ansible.builtin.set_fact:
    setup_cli_tools__helm_url: 'https://get.helm.sh/helm-{{ setup_cli_tools_helm_version }}-darwin-arm64.tar.gz'
    setup_cli_tools_helm_folder: 'darwin-arm64'
  when: 'ansible_facts[''os_family''] == ''Darwin'''

- name: Build URL for Debian
  ansible.builtin.set_fact:
    setup_cli_tools_helm_url: 'https://get.helm.sh/helm-{{ setup_cli_tools_helm_version }}-linux-amd64.tar.gz'
    setup_cli_tools_helm_folder: 'linux-amd64'
  when: 'ansible_facts[''os_family''] in [''Debian'', ''RedHat'' ]'

- name: Download and unarchive helm
  ansible.builtin.unarchive:
    src: "{{ setup_cli_tools_helm_url }}"
    dest: /tmp
    remote_src: true
    mode: '0755'
    include:
      - '{{ setup_cli_tools_helm_folder }}/helm'

- name: Copy Helm
  ansible.builtin.copy:
    src: '/tmp/{{ setup_cli_tools_helm_folder }}/helm'
    dest: '/usr/local/bin/helm'
    remote_src: true
    mode: '0755'

- name: Get ZSH Autocomplete
  ansible.builtin.command:
    cmd: helm completion zsh
  changed_when: false
  register: setup_cli_tools_helm_zsh_completion

- name: Create ZSH autocomple file
  ansible.builtin.copy:
    dest: '/usr/share/zsh/vendor-completions/_helm'
    content: '{{ setup_cli_tools_helm_zsh_completion.stdout }}'
    mode: '0755'

- name: Get Bash Autocomplete
  ansible.builtin.command:
    cmd: helm completion bash
  changed_when: false
  register: setup_cli_tools_helm_bash_completion

- name: Create Bash autocomple file
  ansible.builtin.copy:
    dest: '/etc/bash_completion.d/helm_completion'
    content: '{{ setup_cli_tools_helm_bash_completion.stdout }}'
    mode: '0755'
...
