---
- name: Build URL for Darwin (Mac)
  ansible.builtin.set_facts:
    setup_cli_tools_kubectl_url: 'https://dl.k8s.io/release/{{ setup_cli_tools_kubectl_version }}/bin/darwin/arm64/kubectl'
  when: 'ansible_facts[''os_family''] == ''Darwin'''

- name: Build URL for Debian
  ansible.builtin.set_facts:
    setup_cli_tools_kubectl_url: 'https://dl.k8s.io/release/{{ setup_cli_tools_kubectl_version }}/bin/darwin/amd64/kubectl'
  when: 'ansible_facts[''os_family''] == ''Debian'''

- name: Download kubectl
  ansible.builtin.get_url:
    url: '{{ setup_cli_tools_kubectl_url }}'
    dest: /usr/local/bin/kubectl
    mode: '0755'
...
