---
# You need to install gnu-tar (brew install gnu-tar)
- name: Build URL for Darwin (Mac)
  ansible.builtin.set_fact:
    setup_cli_tools_openshift_install_url: 'https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/{{ setup_cli_tools_openshift_install_version }}/openshift-install-mac-arm64.tar.gz'
  when: 'ansible_facts[''os_family''] == ''Darwin'''

- name: Build URL for Debian
  ansible.builtin.set_fact:
    setup_cli_tools_openshift_install_url: 'https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/{{ setup_cli_tools_openshift_install_version }}/openshift-install-linux.tar.gz'
  when: 'ansible_facts[''os_family''] in [''Debian'', ''RedHat'' ]'

- name: Download and unarchive openshift-install
  ansible.builtin.unarchive:
    src: "{{ setup_cli_tools_openshift_install_url }}"
    dest: /usr/local/bin
    remote_src: true
    mode: '0755'
    include:
      - 'openshift-install'

- name: Get ZSH Autocomplete
  ansible.builtin.command:
    cmd: openshift-install completion zsh
  changed_when: false
  register: setup_cli_tools_openshift_install_zsh_completion

- name: Create ZSH autocomple file
  ansible.builtin.copy:
    dest: '/usr/share/zsh/vendor-completions/_openshift-install'
    content: '{{ setup_cli_tools_openshift_install_zsh_completion.stdout }}'
    mode: '0755'

- name: Get Bash Autocomplete
  ansible.builtin.command:
    cmd: openshift-install completion bash
  changed_when: false
  register: setup_cli_tools_openshift_install_bash_completion

- name: Create Bash autocomple file
  ansible.builtin.copy:
    dest: '/etc/bash_completion.d/openshift-install_completion'
    content: '{{ setup_cli_tools_openshift_install_bash_completion.stdout }}'
    mode: '0755'
...
