---
# You need to install gnu-tar (brew install gnu-tar)
- name: Build URL for Darwin (Mac)
  ansible.builtin.set_facts:
    setup_cli_tools_openshift_install_url: 'https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/{{ setup_cli_tools_openshift_install_version }}/openshift-install-mac-arm64.tar.gz'
  when: 'ansible_facts[''os_family''] == ''Darwin'''

- name: Build URL for Debian
  ansible.builtin.set_facts:
    setup_cli_tools_openshift_install_url: 'https://mirror.openshift.com/pub/openshift-v4/amd64/clients/ocp/{{ setup_cli_tools_openshift_install_version }}/openshift-install-linux.tar.gz'
  when: 'ansible_facts[''os_family''] == ''Debian'''

- name: Download and unarchive openshift-install
  ansible.builtin.unarchive:
    src: "{{ setup_cli_tools_openshift_install_url }}"
    dest: /usr/local/bin
    remote_src: true
    mode: '0755'
    include:
      - 'openshift-install'
...
