---
- name: 'Install starship with brew'
  community.general.homebrew:
    name: 'starship'
    state: 'present'

- name: 'Tap olets/tap'
  community.general.homebrew_tap:
    name: olets/tap
    state: present

- name: 'Install zsh-transient-prompt with brew'
  community.general.homebrew:
    name: 'zsh-transient-prompt'
    state: 'present'

- name: 'Enable starship on zsh'
  ansible.builtin.blockinfile:
    path: '/etc/zshrc'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (p5xeu.general.setup_starship)'
    block: |
      {{ lookup('template', 'zsh/rc.j2') }}

      {{ lookup('template', 'zsh/keybindings.j2') }}

      source /opt/homebrew/share/zsh-transient-prompt/transient-prompt.zsh-theme
  become: true
  become_user: root

- name: 'Enable starship on bash'
  ansible.builtin.blockinfile:
    path: '/etc/bashrc'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (p5xeu.general.setup_starship)'
    block: |
      eval "$(starship init bash)"
  become: true
  become_user: root

- name: 'Create Config directory'
  ansible.builtin.file:
    state: 'directory'
    path: '/etc/starship/'
    owner: 'root'
    group: 'wheel'
    mode: '0755'
  become: true
  become_user: root

- name: 'Template Config'
  ansible.builtin.template:
    src: 'starship.toml.j2'
    dest: '/etc/starship/starship.toml'
    owner: 'root'
    group: 'wheel'
    mode: '0644'
  become: true
  become_user: root
...
