---
- name: 'Install starship'
  ansible.builtin.package:
    name: 'starship'
    state: 'present'
  become: true
  become_user: root

- name: 'Clone zsh-transient-prompt'
  ansible.builtin.git:
    repo: 'https://github.com/olets/zsh-transient-prompt'
    dest: /opt/zsh-transient-prompt
    depth: 1
    single_branch: true
    version: main

- name: 'Enable starship on zsh'
  ansible.builtin.blockinfile:
    path: '/etc/zsh/zshrc'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (p5xeu.general.setup_starship)'
    block: |
      {{ lookup('template', 'zsh/rc.j2') }}

      {{ lookup('template', 'zsh/keybindings.j2') }}

      source /opt/zsh-transient-prompt/transient-prompt.zsh-theme
  become: true
  become_user: root

- name: 'Enable starship on bash'
  ansible.builtin.blockinfile:
    path: '/etc/bash.bashrc'
    marker: '# {mark} ANSIBLE MANAGED BLOCK (p5xeu.general.setup_starship)'
    block: |
      eval "$(starship init bash)"
  become: true
  become_user: root

- name: 'Create Config directory'
  ansible.builtin.file:
    state: 'directory'
    path: '/etc/starship/'
    owner: 'root'
    group: 'root'
    mode: '0755'
  become: true
  become_user: root

- name: 'Template Config'
  ansible.builtin.template:
    src: 'starship.toml.j2'
    dest: '/etc/starship/starship.toml'
    owner: 'root'
    group: 'root'
    mode: '0644'
  become: true
  become_user: root
...
