---
- name: 'OS updates'
  hosts: '{{ target | default("all") }}'
  remote_user: 'root'
  gather_facts: true
  serial: '{{ ansible_serial | default(omit) }}'
  tasks:
    - name: 'Perform Host OS updates'
      ansible.builtin.include_role:
        name: 'p5xeu.general.update_os'
      when: role_update_os_enabled | default(true)
...
